"""empty message

Revision ID: 81032bc7d539
Revises: 
Create Date: 2021-05-13 18:58:28.598915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81032bc7d539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'physicality')
    op.drop_column('players', 'heading')
    op.drop_column('players', 'defending')
    op.drop_column('players', 'goalkeeping')
    op.drop_column('players', 'pace')
    op.drop_column('players', 'dribbling')
    op.drop_column('players', 'shooting')
    op.drop_column('players', 'passing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('passing', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('shooting', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('pace', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('goalkeeping', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('defending', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('heading', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('physicality', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
