"""empty message

Revision ID: f1fefef27af1
Revises: 81032bc7d539
Create Date: 2021-05-13 19:53:22.460808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fefef27af1'
down_revision = '81032bc7d539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint('players_team_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    op.drop_column('players', 'team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_team_fkey', 'players', 'teams', ['team'], ['id'])
    op.drop_column('players', 'team_id')
    # ### end Alembic commands ###
